image: docker:latest

build:
  stage: build
  script:
  - pwd
  - ls
  - ./docker_setup.sh
  - source bbb_build.sh
  artifacts:
    paths:
    - build/downloads
    - build/cache
    - build/sstate-cache
    - build/tmp
