image: docker:latest

before_script:
  - ./docker_setup.sh
  - source oe-init-build-env

build:
  stage: build
  script:
    - bitbake core-image-minimal
  artifacts:
    paths:
    - build/downloads
    - build/cache
    - build/sstate-cache
    - build/tmp
