image: ubuntu:latest

before_script:
  - apt-get -y update
  - apt-get -y install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat libsdl1.2-dev xterm
  - source oe-init-build-env

build:
  stage: build
  script:
    - bitbake core-image-minimal
  artifacts:
    paths:
    - build/downloads
    - build/cache
    - build/sstate-cache
    - build/tmp
