image: docker:latest

build:
  stage: build
  script:
  - pwd
  - ls
  - ./docker_setup.sh
  - source oe-init-build-env
    - bitbake core-image-minimal
  artifacts:
    paths:
    - build/downloads
    - build/cache
    - build/sstate-cache
    - build/tmp
