image: crops/poky

build:
  stage: build
  variables:
    workdir: /workdir
  script:
  - pwd
  - ls
  - ./bbb_build.sh
  artifacts:
    paths:
    - build/downloads
    - build/cache
    - build/sstate-cache
    - build/tmp
