image: crops/poky

build:
  stage: build
  script:
  - pwd
  - ls
  - mv /builds/j-mcavoy/smart-mirror /workdir
  - cd /workdir
  - ./bbb_build.sh
  artifacts:
    paths:
    - build/downloads
    - build/cache
    - build/sstate-cache
    - build/tmp
