image: docker:latest

build:
  stage: build
  script:
  - pwd
  - ls
  - docker run --rm -it -v $(readlink -f .):/workdir crops/poky --workdir=/workdir
  - source bbb_build.sh
  artifacts:
    paths:
    - build/downloads
    - build/cache
    - build/sstate-cache
    - build/tmp
